= Aquila quest
:last-update-label!:
:toc:
:toc-title:

== Thợ rèn

. [1] Đỡ đòn thành công 1 lần - trong cùng 1 trận, rút lui thành công
. [1] Tích lũy đánh bại 8 tiêu khách phe địch
. [1] Tham gia hoàn thành 5 lần nhiệm vụ *[Hộ tống]*
. [1] Trong 1 trận đấu, đánh bại 2 tiêu khách phe địch
. [3] Tích lũy rút lui thành công 3 lần (ít nhất 2 triệu nhật nguyệt kim)
. [2] Nộp 2 [yellow]*[Khóa trường thọ bạc mạ vàng]* và 2 [yellow]*[Lưỡi đao san hô]*
. [3] Trong [orange]*Hiểm cảnh/Kiếp cảnh*, rút lui bằng *[Xích thủy cốc]* 3 lần
. [3] Trong [orange]*Hiểm cảnh/Kiếp cảnh*, tích lũy mở rương Thần hỏa đặc biệt 6 lần *(Ẩn cát/tụ sét/đóng băng)*
. [3] Trong [orange]*Hiểm cảnh/Kiếp cảnh*, tích lũy đánh bại 3 tiêu khách phe địch
  trong thời gian [yellow]*Sơn hải lộ*, [yellow]*Vong ưu lộ* có hiệu lực
. [3] Trong [orange]*Hiểm cảnh/Kiếp cảnh*, dùng chìa khóa mở hang báu 1 lần. Trong cùng trận, mở 2  [magenta]#rương Thần hỏa Ưu# , 1 [yellow]#rương Thần hỏa cực#
. [3] Nộp 2 [yellow]*Bình túy sinh mộng tử*, 1 [red]*Lư phần tâm nhật nguyệt*
. [4] Tích lũy mang ra 8 [yellow]*vũ khí hoặc hộ giáp có phẩm chất từ Cực phẩm trở lên*

== Minh văn

. [1] Tích lũy rút lui thành cồng 3 lần
. [1] Tích lũy giá trị chiến lợi phẩm đạt 3 triệu nhật nguyệt kim
. [1] Tích lũy 10 lần mở *Giá vũ khí*, *Hộp vũ khí*, *Hộp minh văn*
. [1] Tích lũy 8 lần chiếm lấy/quét sạch *Căn cứ đằng quỷ*
. [1] Tích lũy mang ra 6 [yellow]*Di vật cực phẩm trở lên*
. [1] Nộp 2 [yellow]*Vòng trói mệnh*, 2 [yellow]*Lư hương*
. [1] Trong [orange]*Hiểm cảnh/Kiếp cảnh*, tích lũy giá trị chiến lợi phẩm đạt 6 triệu
. [1] Trong [orange]*Hiểm cảnh/Kiếp cảnh*, tích lũy mở 30 rương vật tư bất kỳ tại
  khu vực [green]*Thành Đường An*
. [1] Trong [orange]*Hiểm cảnh/Kiếp cảnh*, tích lũy rút lui 3 lần (ít nhất 1 triệu)
. [1] Trong [orange]*Hiểm cảnh/Kiếp cảnh*, tích lũy mở 30 rương vật tư bất kỳ tại
  khu vực [green]*Côn Lôn Khư*
. [1] Trong [orange]*Hiểm cảnh/Kiếp cảnh*, tích lũy mở 18 *Xe chở khoáng sản*, *Kiệu*, *Giếng nước*
. [1] Trong [orange]*Hiểm cảnh/Kiếp cảnh*, tích lũy mở 30 rương vật tư bất kỳ tại
  khu vực [green]*Điện Thần Ưng*
. [1] Trong [orange]*Hiểm cảnh/Kiếp cảnh*, tích lũy 8 lần chiếm lấy/quét sạch *Căn cứ đằng quỷ*
. [1] Trong [orange]*Hiểm cảnh/Kiếp cảnh*, tích lũy 5 lần hoàn thành *[Trảm nghiệp]* hoặc *[Hoàn trả]* (quest của Đường Tăng)
. [3] Nộp 2 [yellow]*Khóa Thiên cơ*, 1 [red]*Thuyền đêm hoang tần*
. [2] Trong [orange]*Kiếp cảnh*, tích lũy giá trị chiến lợi phẩm đạt 8 triệu (giới hạn tướng: báo, chùa, nước, băng, diệu, cáo, rùa, cyra)
. [2] Trong [orange]*Kiếp cảnh*, tích lũy gây ra 30 000 sát thương cho tiêu khách phe địch (giới hạn tướng: ninh, lửa, yoto,, núi, takeda, hổ, lân, 10k) -- Gây sát thương cho 2 anh ninja trong Côn Lôn/Đường An cũng tính
. [2] Trong [orange]*Kiếp cảnh*, rút lui thành công 5 lần (giới hạn tướng: matari, cát, vô trần, gián, zai, hadi, lil, mộng)
. [2] Trong [orange]*Kiếp cảnh*, tích lũy 8 lần dùng Chìa khóa mở hang báu (hang Khotan tính 2)


[.big-text]
*End quest*


== Hàng rong

Lưu ý: tất cả các quest nộp của hàng rong đều yêu cầu *KHÔNG KHÓA* (ko mua rồi nộp được)

. [2] Nộp 5 [cyan]*Lạc thiết*, 5 [magenta]*Búa thợ rèn*, 5 [cyan]*Ống mực*
. [2] Nộp 5 [magenta]*Kẹo râu rồng*, 5 [magenta]*Kẹo hồ lô*, 5 [magenta]*Bánh trung thu*
. [2] Nộp 5 [magenta]*Thịt bò om*, 5 [magenta]*Gà ăn mày*
. [2] [Mua được] Nộp 1 [red]*Thép côn ngô*, 1 [red]*Thép thiên hỏa*, 1 [red]*Tủy băng*, 1 [red]*Thiên tinh truỵ*
. [3] Nộp 6 minh văn ưu phẩm [magenta]*Xuyên sơn/Trích tinh tác*, 4 minh văn cực phẩm [yellow]*Túi khám phá/Trời ban - cuộn dây*
. [3] Nộp 4 [magenta]*Hộ giáp Ưu phẩm*, 2 [magenta]*Túi đồ Ưu phẩm*
. [3] Nộp 2 [magenta]*Ưu phẩm Đại đao, Trảm mã, Thái đao, Hoành đao, Song kích, Song đao hoặc Trường kiêm*, 2 [magenta]*Vũ khí tầm xa ưu phâm*
. [3] [Mua được] Nộp 2 [red]*Mảnh lông vũ cát quang*, 2 [red]*Vụ hải giao tiêu*,
  2 [red]*Búa thiên công*
. [4] Nộp 1 [red]*Di vật tài liệu sách Thần phẩm*, 1 [red]*Di vật khoáng sản kim loại Thần phẩm*
. [4] Nộp 2 [yellow]*Hộ giáp cực phẩm*, 1 [yellow]*Túi đồ cực phẩm*



++++

<style>

.cyan {
color: rgb(0,180,255);
}

.red {
color: rgb(255,0,0);
}
.magenta {
color: rgb(255,0,255);
}
.orange{
color: rgb(255,120,0);
}

a {
  color: #58a6ff;
  text-decoration: none;
}
a:hover {
  text-decoration: underline;
}


.big-text p {
  font-size: 2em;
}

#footer {
  display: none;
}

body {
  background-color: #0d1117;
  color: #c9d1d9;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, "Helvetica Neue", sans-serif;
  line-height: 1.6;
  padding: 20px;
}

/* Headings */
h1, h2, h3, h4, h5, h6 {
  color: #c9d1d9;
  margin-bottom: 16px;
  font-weight: bold;
}

#header > h1:first-child {
  color: white;
}


</style>
++++
