= Aquila quest
:last-update-label!:
:toc:
:toc-title:

== Thợ rèn

. Đỡ đòn thành công 1 lần - trong cùng 1 trận, rút lui thành công
. Tích lũy đánh bại 8 tiêu khách phe địch
. Tham gia hoàn thành 5 lần nhiệm vụ *[Hộ tống]*
. Trong 1 trận đấu, đánh bại 2 tiêu khách phe địch
. Tích lũy rút lui thành công 3 lần (ít nhất 2 triệu nhật nguyệt kim)
. Nộp 2 *[Khóa trường thọ bạc mạ vàng]* và 2 *[Lưỡi đao san hô]*
. Trong *Hiểm cảnh/Kiếp cảnh*, rút lui bằng *[Xích thủy cốc]* 3 lần
. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy mở rương Thần hỏa đặc biệt 6 lần *(Ẩn cát/tụ sét/đóng băng)*
. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy đánh bại 3 tiêu khách phe địch trong thời gian *[Sơn hải lộ]*, *[Vong ưu lộ]* có hiệu lực
. Trong *Hiểm cảnh/Kiếp cảnh*, dùng chìa khóa mở hang báu 1 lần. Trong cùng trận, mở 2 rương Thần hỏa Ưu (tím), 1 rương Thần hỏa cực (vàng)
. Nộp 2 *Bình túy sinh mộng tử*, 1 *Lư phần tâm nhật nguyệt*
. Tích lũy mang ra 8 *vũ khí hoặc hộ giáp có phẩm chất từ Cực phẩm trở lên*

== Minh văn

. Tích lũy rút lui thành cồng 3 lần
. Tích lũy giá trị chiến lợi phẩm đạt 3 triệu nhật nguyệt kim
. Tích lũy 10 lần mở *Giá vũ khí*, *Hộp vũ khí*, *Hộp minh văn*
. Tích lũy 8 lần chiếm lấy/quét sạch *Căn cứ đằng quỷ*
. Tích lũy mang ra 6 *Di vật cực phẩm trở lên*
. Nộp 2 *Vòng trói mệnh*, 2 *Lư hương*
. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy giá trị chiến lợi phẩm đạt 6 triệu
. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy mở 30 rương vật tư bất kỳ tại khu vực *Thành Đường An*
. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy rút lui 3 lần (ít nhất 1 triệu)
. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy mở 30 rương vật tư bất kỳ tại khu vực *Côn Lôn Khư*
. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy mở 18 *Xe chở khoáng sản*, *Kiệu*, *Giếng nước*
. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy mở 30 rương vật tư bất kỳ tại khu vực *Điện Thần Ưng*
. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy 8 lần chiếm lấy/quét sạch *Căn cứ đằng quỷ*
. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy 5 lần hoàn thành *[Trảm nghiệp]* hoặc *[Hoàn trả]* (quest của Đường Tăng)
. Nộp 2 *Khóa Thiên cơ*, 1 *Thuyền đêm hoang tần*
. Trong *Kiếp cảnh*, tích lũy giá trị chiến lợi phẩm đạt 8 triệu (giới hạn tướng: báo, chùa, nước, băng, diệu, cáo, rùa, cyra)
. Trong *Kiếp cảnh*, tích lũy gây ra 30 000 sát thương cho tiêu khách phe địch (giới hạn tướng: ninh, lửa, yoto,, núi, takeda, hổ, lân, 10k) -- Gây sát thương cho 2 anh ninja trong Côn Lôn/Đường An cũng tính
. Trong *Kiếp cảnh*, rút lui thành công 5 lần (giới hạn tướng: matari, cát, vô trần, gián, zai, hadi, lil, mộng)
. Trong *Kiếp cảnh*, tích lũy 8 lần dùng Chìa khóa mở hang báu (hang Khotan tính 2)

[.big-text]
*End quest*

++++
<style>
.big-text {
  font-size: 2em;
}
</style>
++++


== Hàng rong

Lưu ý: tất cả các quest nộp của hàng rong đều yêu cầu *KHÔNG KHÓA* (ko mua rồi nộp được)

. Nộp 5 *Lạc thiết* (xanh), 5 *Búa thợ rèn* (tím), 5 *Ống mực* (xanh)
. Nộp 5 *Kẹo râu rồng* (tím), 5 *Kẹo hồ lô* (tím), 5 *Bánh trung thu* (tím)
. Nộp 5 *Thịt bò om* (tím), 5 *Gà ăn mày*
. Nộp 1 *Thép côn ngô* (đỏ), 1 *Thép thiên hỏa* (đỏ), 1 *Tủy băng* (đỏ), 1 *Thiên tinh truỵ* (đỏ)
. Nộp 6 minh văn ưu phẩm *Xuyên sơn/Trích tinh tác*, 4 minh văn cực phẩm *Túi khám phá/Trời ban - cuộn dây*

++++
<style>
#footer {
  display: none;
}
</style>
++++
