= Aquila quest
:last-update-label!:
:toc:

== Thợ rèn

1. Đỡ đòn thành công 1 lần - trong cùng 1 trận, rút lui thành công
2. Tích lũy đánh bại 8 tiêu khách phe địch
3. Tham gia hoàn thành 5 lần nhiệm vụ *[Hộ tống]*
4. Trong 1 trận đấu, đánh bại 2 tiêu khách phe địch
5. Tích lũy rút lui thành công 3 lần (ít nhất 2 triệu nhật nguyệt kim)
6. Nộp 2 *[Khóa trường thọ bạc mạ vàng]* và 2 *[Lưỡi đao san hô]*
7. Trong *Hiểm cảnh/Kiếp cảnh*, rút lui bằng *[Xích thủy cốc]* 3 lần
8. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy mở rương Thần hỏa đặc biệt 6 lần *(Ẩn cát/tụ sét/đóng băng)*
9. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy đánh bại 3 tiêu khách phe địch trong thời gian *[Sơn hải lộ]*, *[Vong ưu lộ]* có hiệu lực
10. Trong *Hiểm cảnh/Kiếp cảnh*, dùng chìa khóa mở hang báu 1 lần. Trong cùng trận, mở 2 rương Thần hỏa Ưu (tím), 1 rương Thần hỏa cực (vàng)
11. Nộp 2 *Bình túy sinh mộng tử*, 1 *Lư phần tâm nhật nguyệt*
12. Tích lũy mang ra 8 *vũ khí hoặc hộ giáp có phẩm chất từ Cực phẩm trở lên*

== Minh văn

1. Tích lũy rút lui thành cồng 3 lần
2. Tích lũy giá trị chiến lợi phẩm đạt 3 triệu nhật nguyệt kim
3. Tích lũy 10 lần mở *Giá vũ khí*, *Hộp vũ khí*, *Hộp minh văn*
4. Tích lũy 8 lần chiếm lấy/quét sạch *Căn cứ đằng quỷ*
5. Tích lũy mang ra 6 *Di vật cực phẩm trở lên*
6. Nộp 2 *Vòng trói mệnh*, 2 *Lư hương*
7. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy giá trị chiến lợi phẩm đạt 6 triệu
8. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy mở 30 rương vật tư bất kỳ tại khu vực *Thành Đường An*
9. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy rút lui 3 lần (ít nhất 1 triệu)
10. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy mở 30 rương vật tư bất kỳ tại khu vực *Côn Lôn Khư*
11. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy mở 18 *Xe chở khoáng sản*, *Kiệu*, *Giếng nước*
12. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy mở 30 rương vật tư bất kỳ tại khu vực *Điện Thần Ưng*
13. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy 8 lần chiếm lấy/quét sạch *Căn cứ đằng quỷ*
14. Trong *Hiểm cảnh/Kiếp cảnh*, tích lũy 5 lần hoàn thành *[Trảm nghiệp]* hoặc *[Hoàn trả]* (quest của Đường Tăng)
15. Nộp 2 *Khóa Thiên cơ*, 1 *Thuyền đêm hoang tần*
16. Trong *Kiếp cảnh*, tích lũy giá trị chiến lợi phẩm đạt 8 triệu (giới hạn tướng: báo, chùa, nước, băng, diệu, cáo, rùa, cyra)
17. Trong *Kiếp cảnh*, tích lũy gây ra 30 000 sát thương cho tiêu khách phe địch (giới hạn tướng: ninh, lửa, yoto,, núi, takeda, hổ, lân, 10k) -- Gây sát thương cho 2 anh ninja trong Côn Lôn/Đường An cũng tính
18. Trong *Kiếp cảnh*, rút lui thành công 5 lần (giới hạn tướng: matari, cát, vô trần, gián, zai, hadi, lil, mộng)
19. Trong *Kiếp cảnh*, tích lũy 8 lần dùng Chìa khóa mở hang báu


== Hàng rong

Lưu ý: tất cả các quest nộp của hàng rong đều yêu cầu *KHÔNG KHÓA* (ko mua rồi nộp được)

1. Nộp 5 *Lạc thiết* (xanh), 5 *Búa thợ rèn* (tím), 5 *Ống mực* (xanh)
2. Nộp 5 *Kẹo râu rồng* (tím), 5 *Kẹo hồ lô* (tím), 5 *Bánh trung thu* (tím)
3. Nộp 5 *Thịt bò om* (tím), 5 *Gà ăn mày*
4. Nộp 1 *Thép côn ngô* (đỏ), 1 *Thép thiên hỏa* (đỏ), 1 *Tủy băng* (đỏ), 1 *Thiên tinh truỵ* (đỏ)
5. Nộp 6 minh văn ưu phẩm *Xuyên sơn/Trích tinh tác*, 4 minh văn cực phẩm *Túi khám phá/Trời ban - cuộn dây*
